apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dyyun-reader
  namespace: dyyun
rules:
  - apiGroups: [""]
    resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
    verbs: ["get", "list", "watch"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dyyun-reader-binding
  namespace: dyyun
subjects:
- kind: ServiceAccount
  name: default
  apiGroup: ""
roleRef:
  kind: Role
  name: dyyun-reader
  apiGroup: ""